use std::{path::PathBuf, str::FromStr};

use vv_compiler::compile_assets_root;
use vv_planet::PlanetGeometry;
use vv_registry::{CompiledFloraFeature, ContentKey};

use crate::PlanetTerrain;

#[test]
fn terrain_generation_is_deterministic_and_uses_registry_surface_block() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");
    let content = compile_assets_root(&assets).expect("core content should compile");
    let worldgen = content.worldgen_content();
    let geometry = PlanetGeometry::with_resolution(32.0, 0.5, 16);
    let cfg = vv_config::WorldGenConfig::default();

    let a = PlanetTerrain::generate_for_geometry(geometry, &cfg, &worldgen).expect("terrain a");
    let b = PlanetTerrain::generate_for_geometry(geometry, &cfg, &worldgen).expect("terrain b");

    for (face, u, v) in [(0, 4, 4), (1, 7, 3), (5, 9, 12)] {
        assert_eq!(a.get_height(face, u, v), b.get_height(face, u, v));
        assert_eq!(a.get_biome(face, u, v), b.get_biome(face, u, v));
        assert_eq!(
            a.get_surface_block(face, u, v),
            b.get_surface_block(face, u, v)
        );
    }

    assert!(content.blocks.key(a.get_surface_block(0, 4, 4)).is_some());
}

#[test]
fn alpha_resources_are_generated_from_content_defs() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");
    let content = compile_assets_root(&assets).expect("core content should compile");
    let worldgen = content.worldgen_content();
    let geometry = PlanetGeometry::with_resolution(64.0, 0.5, 64);
    let resolution = geometry.resolution;

    let terrain = PlanetTerrain::generate_for_geometry(
        geometry,
        &vv_config::WorldGenConfig::default(),
        &worldgen,
    )
    .expect("terrain should generate");

    let wood_log = content
        .blocks
        .id(&ContentKey::from_str("voxelverse:wood_log").unwrap())
        .expect("wood_log block");

    let coal_ore = content
        .blocks
        .id(&ContentKey::from_str("voxelverse:coal_ore").unwrap())
        .expect("coal_ore block");

    let iron_ore = content
        .blocks
        .id(&ContentKey::from_str("voxelverse:iron_ore").unwrap())
        .expect("iron_ore block");

    let water = content
        .blocks
        .id(&ContentKey::from_str("voxelverse:water").unwrap())
        .expect("water block");

    let mut found_wood = false;
    let mut found_coal = false;
    let mut found_iron = false;
    let mut found_water = false;

    for face in 0..6 {
        for u in (0..resolution).step_by(2) {
            for v in (0..resolution).step_by(2) {
                for layer in terrain.feature_candidate_layers(face, u, v) {
                    if terrain.generated_feature_block(face, u, v, layer) == Some(wood_log) {
                        found_wood = true;
                    }
                }

                if terrain.get_surface_block(face, u, v) == water {
                    found_water = true;
                }

                let height = terrain.get_height(face, u, v);

                for depth in 1..=32 {
                    let Some(layer) = height.checked_sub(depth) else {
                        continue;
                    };

                    match terrain.get_block(face, u, v, layer) {
                        block if block == coal_ore => found_coal = true,
                        block if block == iron_ore => found_iron = true,
                        _ => {}
                    }
                }
            }
        }
    }

    assert!(found_wood, "wood should be generated by flora defs");
    assert!(found_coal, "coal should be generated by ore defs");
    assert!(found_iron, "iron should be generated by ore defs");
    assert!(
        found_water,
        "water should be generated by biome surface defs"
    );
}

#[test]
fn biome_boundaries_do_not_create_cliff_steps() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");
    let content = compile_assets_root(&assets).expect("core content should compile");
    let geometry = PlanetGeometry::with_resolution(96.0, 0.5, 96);

    let terrain = PlanetTerrain::generate_for_geometry(
        geometry,
        &vv_config::WorldGenConfig::default(),
        &content.worldgen_content(),
    )
    .expect("terrain should generate");

    let mut checked_boundaries = 0;
    let mut largest_step_m = 0.0f32;

    for face in 0..6 {
        for u in 0..95 {
            for v in 0..95 {
                for (nu, nv) in [(u + 1, v), (u, v + 1)] {
                    if terrain.get_biome(face, u, v) == terrain.get_biome(face, nu, nv) {
                        continue;
                    }

                    checked_boundaries += 1;

                    let step_layers = terrain
                        .get_height(face, u, v)
                        .abs_diff(terrain.get_height(face, nu, nv));

                    largest_step_m = largest_step_m.max(geometry.voxel_extent_m(step_layers));
                }
            }
        }
    }

    assert!(
        checked_boundaries > 0,
        "test seed should contain biome boundaries"
    );

    assert!(
        largest_step_m <= 3.0,
        "biome boundary height step should stay walkable, got {largest_step_m} m"
    );
}

#[test]
fn same_seed_with_different_voxel_size_keeps_planet_radius_m() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");
    let content = compile_assets_root(&assets).expect("core content should compile");

    let mut coarse_settings = content.world;
    coarse_settings.voxel_size_m = 0.5;

    let mut fine_settings = content.world;
    fine_settings.voxel_size_m = 0.05;

    let cfg = vv_config::WorldGenConfig::default();

    let coarse = PlanetTerrain::generate(&cfg, &content.worldgen_content(), &coarse_settings)
        .expect("coarse terrain");

    let fine = PlanetTerrain::generate(&cfg, &content.worldgen_content(), &fine_settings)
        .expect("fine terrain");

    assert_eq!(coarse.geometry().radius_m, fine.geometry().radius_m);
    assert!(fine.geometry().resolution > coarse.geometry().resolution);
}

#[test]
fn same_world_params_keep_global_terrain_shape_in_meters() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");
    let content = compile_assets_root(&assets).expect("core content should compile");
    let worldgen = content.worldgen_content();
    let cfg = vv_config::WorldGenConfig::default();

    let coarse_geometry = PlanetGeometry::new(128.0, 0.5);
    let fine_geometry = PlanetGeometry::new(128.0, 0.25);

    let coarse = PlanetTerrain::generate_for_geometry(coarse_geometry, &cfg, &worldgen)
        .expect("coarse terrain");

    let fine =
        PlanetTerrain::generate_for_geometry(fine_geometry, &cfg, &worldgen).expect("fine terrain");

    for (face, u_frac, v_frac) in [(0, 0.25, 0.25), (2, 0.5, 0.75), (5, 0.8, 0.4)] {
        let coarse_u = (coarse_geometry.resolution as f32 * u_frac) as u32;
        let coarse_v = (coarse_geometry.resolution as f32 * v_frac) as u32;
        let fine_u = (fine_geometry.resolution as f32 * u_frac) as u32;
        let fine_v = (fine_geometry.resolution as f32 * v_frac) as u32;

        let coarse_height_m = coarse_geometry
            .layer_radius_m(coarse.get_height(face, coarse_u, coarse_v))
            - coarse_geometry.radius_m;

        let fine_height_m = fine_geometry.layer_radius_m(fine.get_height(face, fine_u, fine_v))
            - fine_geometry.radius_m;

        assert!(
            (coarse_height_m - fine_height_m).abs() <= coarse_geometry.voxel_size_m * 2.0,
            "terrain height drifted: coarse {coarse_height_m}, fine {fine_height_m}"
        );
    }
}

#[test]
fn authored_tree_height_is_physical_and_voxelized_by_density() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");
    let content = compile_assets_root(&assets).expect("core content should compile");

    let oak = content
        .flora
        .id(&ContentKey::from_str("voxelverse:oak_trees").unwrap())
        .and_then(|id| content.flora.get(id))
        .expect("oak flora");

    let CompiledFloraFeature::Tree {
        trunk_height_max_m, ..
    } = oak.feature
    else {
        panic!("oak_trees should be a tree feature");
    };

    let coarse = PlanetGeometry::new(128.0, 0.5);
    let fine = PlanetGeometry::new(128.0, 0.05);

    let coarse_layers = coarse.meters_to_voxels_ceil(trunk_height_max_m);
    let fine_layers = fine.meters_to_voxels_ceil(trunk_height_max_m);

    assert_eq!(trunk_height_max_m, 7.5);
    assert_eq!(coarse_layers, 15);
    assert_eq!(fine_layers, 150);
    assert!((coarse.voxel_extent_m(coarse_layers) - 7.5).abs() <= coarse.voxel_size_m);
    assert!((fine.voxel_extent_m(fine_layers) - 7.5).abs() <= fine.voxel_size_m);
}
