//! Compiled block families and per-variant `BlockStateValue`.
//!
//! Each `RawBlockDef` produces exactly one `CompiledBlockFamily`. If the
//! block declares no `states`, the family has a single variant; otherwise
//! the cartesian product of every property's value list yields one
//! `VoxelId` per combination.
//!
//! Determinism:
//! - properties are read from the raw `BTreeMap<String, _>` in lexicographic
//!   key order, so the property axis order is stable;
//! - each property kind has a fixed canonical value order in the object
//!   compiler — no implicit alphabetical sort, no host-locale surprises;
//! - the cartesian product is generated by an odometer over those ordered
//!   lists, so two identical packs always produce the exact same sequence
//!   of `VoxelId`s.

use std::collections::{BTreeMap, HashMap};
use std::fmt;
use vv_content_schema::RawBlockStateProperty;
use vv_voxel::VoxelId;

/// Hard cap on variants per family. The compiler errors out beyond this.
pub const MAX_VARIANTS_PER_FAMILY: usize = 256;

/// A specific assignment of every state property to one of its values.
///
/// Stored as a `BTreeMap` so equality, hashing, and iteration are
/// deterministic regardless of insertion order. The empty value
/// represents the lone variant of a stateless block.
#[derive(Clone, Debug, Default, Eq, Hash, PartialEq)]
pub struct BlockStateValue {
    values: BTreeMap<String, String>,
}

impl BlockStateValue {
    pub fn empty() -> Self {
        Self::default()
    }

    pub fn from_btree(values: BTreeMap<String, String>) -> Self {
        Self { values }
    }

    pub fn iter(&self) -> impl Iterator<Item = (&str, &str)> {
        self.values.iter().map(|(k, v)| (k.as_str(), v.as_str()))
    }

    pub fn get(&self, name: &str) -> Option<&str> {
        self.values.get(name).map(String::as_str)
    }

    pub fn is_empty(&self) -> bool {
        self.values.is_empty()
    }

    pub fn len(&self) -> usize {
        self.values.len()
    }
}

impl fmt::Display for BlockStateValue {
    /// Pretty `axis=y,waterlogged=false` form for diagnostics.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.values.is_empty() {
            return f.write_str("(default)");
        }
        let mut first = true;
        for (k, v) in &self.values {
            if !first {
                f.write_str(",")?;
            }
            first = false;
            write!(f, "{k}={v}")?;
        }
        Ok(())
    }
}

/// A group of `VoxelId`s sharing a `family_key` and a state schema.
#[derive(Clone, Debug)]
pub struct CompiledBlockFamily {
    pub family_key: String,
    pub state_schema: BTreeMap<String, RawBlockStateProperty>,
    /// All variants in canonical cartesian order. Length is at least 1.
    pub variants: Vec<VoxelId>,
    pub default_variant: VoxelId,
    pub state_to_id: HashMap<BlockStateValue, VoxelId>,
    pub id_to_state: HashMap<VoxelId, BlockStateValue>,
}

impl CompiledBlockFamily {
    pub fn lookup(&self, state: &BlockStateValue) -> Option<VoxelId> {
        self.state_to_id.get(state).copied()
    }

    pub fn state_of(&self, id: VoxelId) -> Option<&BlockStateValue> {
        self.id_to_state.get(&id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn block_state_value_display_is_stable() {
        let mut combo = BTreeMap::new();
        combo.insert("waterlogged".into(), "false".into());
        combo.insert("axis".into(), "y".into());
        let v = BlockStateValue::from_btree(combo);
        assert_eq!(format!("{v}"), "axis=y,waterlogged=false");
        let empty = BlockStateValue::empty();
        assert_eq!(format!("{empty}"), "(default)");
    }
}
