//! Compiled block families and per-variant `BlockStateValue`.
//!
//! Each `RawBlockDef` produces exactly one `CompiledBlockFamily`. If the
//! block declares no `states`, the family has a single variant; otherwise
//! the cartesian product of every property's value list yields one
//! `VoxelId` per combination.
//!
//! Determinism:
//! - properties are read from the raw `BTreeMap<String, _>` in lexicographic
//!   key order, so the property axis order is stable;
//! - each property kind has a fixed canonical value order (see
//!   [`canonical_values`]) — no implicit alphabetical sort, no host-locale
//!   surprises;
//! - the cartesian product is generated by an odometer over those ordered
//!   lists, so two identical packs always produce the exact same sequence
//!   of `VoxelId`s.

use std::collections::{BTreeMap, HashMap};
use std::fmt;
use vv_content_schema::{RawBlockStateProperty, RawBlockStates};
use vv_voxel::VoxelId;

/// Hard cap on variants per family. The compiler errors out beyond this.
pub const MAX_VARIANTS_PER_FAMILY: usize = 256;

/// A specific assignment of every state property to one of its values.
///
/// Stored as a `BTreeMap` so equality, hashing, and iteration are
/// deterministic regardless of insertion order. The empty value
/// represents the lone variant of a stateless block.
#[derive(Clone, Debug, Default, Eq, Hash, PartialEq)]
pub struct BlockStateValue {
    values: BTreeMap<String, String>,
}

impl BlockStateValue {
    pub fn empty() -> Self {
        Self::default()
    }

    pub fn from_btree(values: BTreeMap<String, String>) -> Self {
        Self { values }
    }

    pub fn iter(&self) -> impl Iterator<Item = (&str, &str)> {
        self.values.iter().map(|(k, v)| (k.as_str(), v.as_str()))
    }

    pub fn get(&self, name: &str) -> Option<&str> {
        self.values.get(name).map(String::as_str)
    }

    pub fn is_empty(&self) -> bool {
        self.values.is_empty()
    }

    pub fn len(&self) -> usize {
        self.values.len()
    }
}

impl fmt::Display for BlockStateValue {
    /// Pretty `axis=y,waterlogged=false` form for diagnostics.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.values.is_empty() {
            return f.write_str("(default)");
        }
        let mut first = true;
        for (k, v) in &self.values {
            if !first {
                f.write_str(",")?;
            }
            first = false;
            write!(f, "{k}={v}")?;
        }
        Ok(())
    }
}

/// A group of `VoxelId`s sharing a `family_key` and a state schema.
#[derive(Clone, Debug)]
pub struct CompiledBlockFamily {
    pub family_key: String,
    pub state_schema: BTreeMap<String, RawBlockStateProperty>,
    /// All variants in canonical cartesian order. Length is at least 1.
    pub variants: Vec<VoxelId>,
    pub default_variant: VoxelId,
    pub state_to_id: HashMap<BlockStateValue, VoxelId>,
    pub id_to_state: HashMap<VoxelId, BlockStateValue>,
}

impl CompiledBlockFamily {
    pub fn lookup(&self, state: &BlockStateValue) -> Option<VoxelId> {
        self.state_to_id.get(state).copied()
    }

    pub fn state_of(&self, id: VoxelId) -> Option<&BlockStateValue> {
        self.id_to_state.get(&id)
    }
}

/// Canonical value order for a state property. Built-in kinds use a fixed
/// sequence so packs and pack-mods generate identical `VoxelId`s; `Enum`
/// preserves the order declared by the author.
pub fn canonical_values(prop: &RawBlockStateProperty) -> Vec<String> {
    match prop {
        RawBlockStateProperty::Axis { .. } => vec!["x".into(), "y".into(), "z".into()],
        RawBlockStateProperty::FacingHorizontal { .. } => {
            vec!["north".into(), "south".into(), "east".into(), "west".into()]
        }
        RawBlockStateProperty::Facing { .. } => vec![
            "north".into(),
            "south".into(),
            "east".into(),
            "west".into(),
            "up".into(),
            "down".into(),
        ],
        RawBlockStateProperty::Half { .. } => vec!["bottom".into(), "top".into()],
        RawBlockStateProperty::StairShape { .. } => vec![
            "straight".into(),
            "inner_left".into(),
            "inner_right".into(),
            "outer_left".into(),
            "outer_right".into(),
        ],
        RawBlockStateProperty::Bool { .. } => vec!["false".into(), "true".into()],
        RawBlockStateProperty::Enum { values, .. } => values.clone(),
    }
}

/// Default value as a string, used to identify the default variant.
pub fn default_value(prop: &RawBlockStateProperty) -> String {
    match prop {
        RawBlockStateProperty::Axis { default }
        | RawBlockStateProperty::FacingHorizontal { default }
        | RawBlockStateProperty::Facing { default }
        | RawBlockStateProperty::Half { default }
        | RawBlockStateProperty::StairShape { default }
        | RawBlockStateProperty::Enum { default, .. } => default.clone(),
        RawBlockStateProperty::Bool { default } => {
            if *default {
                "true".into()
            } else {
                "false".into()
            }
        }
    }
}

/// Generate every `BlockStateValue` for a state schema in canonical order.
/// A schema with no properties returns a single empty `BlockStateValue`.
pub fn enumerate_variants(states: &RawBlockStates) -> Vec<BlockStateValue> {
    if states.properties.is_empty() {
        return vec![BlockStateValue::empty()];
    }

    let names: Vec<&str> = states.properties.keys().map(String::as_str).collect();
    let value_lists: Vec<Vec<String>> = states
        .properties
        .values()
        .map(canonical_values)
        .collect();
    let total: usize = value_lists.iter().map(Vec::len).product();

    let mut result = Vec::with_capacity(total);
    let mut indices = vec![0usize; names.len()];
    loop {
        let mut combo = BTreeMap::new();
        for (i, name) in names.iter().enumerate() {
            combo.insert(name.to_string(), value_lists[i][indices[i]].clone());
        }
        result.push(BlockStateValue::from_btree(combo));

        // Odometer increment, last index varying fastest.
        let mut k = names.len();
        loop {
            if k == 0 {
                return result;
            }
            k -= 1;
            indices[k] += 1;
            if indices[k] < value_lists[k].len() {
                break;
            }
            indices[k] = 0;
        }
    }
}

/// Compute the default `BlockStateValue` from declared per-property defaults.
pub fn default_state(states: &RawBlockStates) -> BlockStateValue {
    let mut combo = BTreeMap::new();
    for (name, prop) in &states.properties {
        combo.insert(name.clone(), default_value(prop));
    }
    BlockStateValue::from_btree(combo)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn axis(default: &str) -> RawBlockStateProperty {
        RawBlockStateProperty::Axis {
            default: default.into(),
        }
    }

    fn bool_prop(default: bool) -> RawBlockStateProperty {
        RawBlockStateProperty::Bool { default }
    }

    #[test]
    fn empty_states_produce_one_empty_variant() {
        let states = RawBlockStates::default();
        let variants = enumerate_variants(&states);
        assert_eq!(variants.len(), 1);
        assert!(variants[0].is_empty());
    }

    #[test]
    fn axis_produces_three_variants_in_xyz_order() {
        let mut states = RawBlockStates::default();
        states.properties.insert("axis".into(), axis("y"));
        let variants = enumerate_variants(&states);
        assert_eq!(variants.len(), 3);
        assert_eq!(variants[0].get("axis"), Some("x"));
        assert_eq!(variants[1].get("axis"), Some("y"));
        assert_eq!(variants[2].get("axis"), Some("z"));
    }

    #[test]
    fn bool_produces_two_variants_false_then_true() {
        let mut states = RawBlockStates::default();
        states
            .properties
            .insert("powered".into(), bool_prop(false));
        let variants = enumerate_variants(&states);
        assert_eq!(variants.len(), 2);
        assert_eq!(variants[0].get("powered"), Some("false"));
        assert_eq!(variants[1].get("powered"), Some("true"));
    }

    #[test]
    fn axis_and_bool_produce_six_variants_with_axis_outer() {
        let mut states = RawBlockStates::default();
        states.properties.insert("axis".into(), axis("y"));
        states
            .properties
            .insert("waterlogged".into(), bool_prop(false));
        let variants = enumerate_variants(&states);
        assert_eq!(variants.len(), 6);
        // axis comes first lexicographically; it varies slowest in our
        // odometer (last index varies fastest), so the outer loop is axis.
        let projection: Vec<(String, String)> = variants
            .iter()
            .map(|v| {
                (
                    v.get("axis").unwrap().to_string(),
                    v.get("waterlogged").unwrap().to_string(),
                )
            })
            .collect();
        assert_eq!(
            projection,
            vec![
                ("x".into(), "false".into()),
                ("x".into(), "true".into()),
                ("y".into(), "false".into()),
                ("y".into(), "true".into()),
                ("z".into(), "false".into()),
                ("z".into(), "true".into()),
            ]
        );
    }

    #[test]
    fn default_state_combines_declared_defaults() {
        let mut states = RawBlockStates::default();
        states.properties.insert("axis".into(), axis("z"));
        states
            .properties
            .insert("waterlogged".into(), bool_prop(true));
        let d = default_state(&states);
        assert_eq!(d.get("axis"), Some("z"));
        assert_eq!(d.get("waterlogged"), Some("true"));
    }

    #[test]
    fn enumeration_is_deterministic_across_runs() {
        let mut states = RawBlockStates::default();
        states.properties.insert("axis".into(), axis("y"));
        states.properties.insert(
            "color".into(),
            RawBlockStateProperty::Enum {
                values: vec!["red".into(), "green".into()],
                default: "red".into(),
            },
        );
        let a = enumerate_variants(&states);
        let b = enumerate_variants(&states);
        assert_eq!(a, b);
    }

    #[test]
    fn block_state_value_display_is_stable() {
        let mut combo = BTreeMap::new();
        combo.insert("waterlogged".into(), "false".into());
        combo.insert("axis".into(), "y".into());
        let v = BlockStateValue::from_btree(combo);
        assert_eq!(format!("{v}"), "axis=y,waterlogged=false");
        let empty = BlockStateValue::empty();
        assert_eq!(format!("{empty}"), "(default)");
    }
}
