param(
    [string]$BlockRoot = "assets\packs\voxelverse_core\defs\blocks",
    [string]$MarkdownOut = "docs\content\BLOCK_VISUAL_CATALOG.md",
    [string]$RonOut = "tools\voxelverse\block_visual_presets\catalog.generated.ron"
)

$ErrorActionPreference = "Stop"

function Find-VoxelVerseRoot {
    $dir = (Get-Location).Path

    while ($true) {
        if ((Test-Path (Join-Path $dir "Cargo.toml")) -and
            (Test-Path (Join-Path $dir "assets"))) {
            return (Resolve-Path $dir).Path
        }

        $parent = Split-Path $dir -Parent
        if ([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $dir) {
            throw "Repo root not found."
        }

        $dir = $parent
    }
}

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    $folder = Split-Path $Path -Parent
    if (!(Test-Path $folder)) { New-Item -ItemType Directory -Force -Path $folder | Out-Null }
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Get-FirstRegexGroup {
    param([string]$Text, [string]$Pattern, [string]$Default = "")
    $match = [regex]::Match($Text, $Pattern)
    if ($match.Success) { return $match.Groups[1].Value }
    return $Default
}

$Root = Find-VoxelVerseRoot
Set-Location $Root

$blockPath = Join-Path $Root $BlockRoot
if (!(Test-Path $blockPath)) {
    throw "Block root not found: $blockPath"
}

$files = Get-ChildItem -Path $blockPath -Filter "*.ron" -Recurse
$entries = @()

foreach ($file in $files) {
    $text = Get-Content -Path $file.FullName -Raw
    $relative = Resolve-Path -Path $file.FullName -Relative

    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    $display = Get-FirstRegexGroup -Text $text -Pattern 'display_key:\s*Some\("([^"]+)"\)' -Default ""
    $material = Get-FirstRegexGroup -Text $text -Pattern 'material:\s*\(\s*kind:\s*([a-zA-Z0-9_]+)' -Default "unknown"
    $program = Get-FirstRegexGroup -Text $text -Pattern 'program:\s*\(\s*type:\s*"([^"]+)"' -Default "flat"
    $pattern = Get-FirstRegexGroup -Text $text -Pattern 'pattern:\s*"([^"]+)"' -Default ""
    $base = Get-FirstRegexGroup -Text $text -Pattern 'base_color:\s*"([^"]+)"' -Default ""
    $family = "core"

    if ($relative.Contains("\generated\blueprints\") -or $relative.Contains("/generated/blueprints/")) {
        $family = "generated_blueprints"
    }
    elseif ($relative.Contains("\generated\matrix\") -or $relative.Contains("/generated/matrix/")) {
        $family = "generated_matrix"
    }
    elseif ($relative.Contains("\generated\") -or $relative.Contains("/generated/")) {
        $family = "generated"
    }

    $entries += [pscustomobject]@{
        Name = $name
        DisplayKey = $display
        Family = $family
        Material = $material
        Program = $program
        Pattern = $pattern
        Base = $base
        Path = $relative
    }
}

$entries = $entries | Sort-Object Family, Name

$md = New-Object System.Text.StringBuilder
[void]$md.AppendLine("# Block visual catalog")
[void]$md.AppendLine("")
[void]$md.AppendLine("Generated by `scripts/Export-VoxelBlockCatalog.ps1`.")
[void]$md.AppendLine("")
[void]$md.AppendLine("| Family | Block | Material | Program | Pattern | Base | File |")
[void]$md.AppendLine("|---|---|---|---|---|---|---|")

foreach ($entry in $entries) {
    [void]$md.AppendLine("| $($entry.Family) | $($entry.Name) | $($entry.Material) | $($entry.Program) | $($entry.Pattern) | $($entry.Base) | `$($entry.Path)` |")
}

$ron = New-Object System.Text.StringBuilder
[void]$ron.AppendLine("[")
foreach ($entry in $entries) {
    [void]$ron.AppendLine("    (")
    [void]$ron.AppendLine("        name: `"$($entry.Name)`",")
    [void]$ron.AppendLine("        display_key: `"$($entry.DisplayKey)`",")
    [void]$ron.AppendLine("        family: `"$($entry.Family)`",")
    [void]$ron.AppendLine("        material: `"$($entry.Material)`",")
    [void]$ron.AppendLine("        program: `"$($entry.Program)`",")
    [void]$ron.AppendLine("        pattern: `"$($entry.Pattern)`",")
    [void]$ron.AppendLine("        base: `"$($entry.Base)`",")
    [void]$ron.AppendLine("        path: `"$($entry.Path.Replace("\", "/"))`",")
    [void]$ron.AppendLine("    ),")
}
[void]$ron.AppendLine("]")

Write-Utf8NoBom -Path (Join-Path $Root $MarkdownOut) -Content $md.ToString()
Write-Utf8NoBom -Path (Join-Path $Root $RonOut) -Content $ron.ToString()

Write-Host "Exported catalog: $MarkdownOut" -ForegroundColor Green
Write-Host "Exported catalog data: $RonOut" -ForegroundColor Green
Write-Host "Catalog entries: $($entries.Count)" -ForegroundColor Cyan