#include "include/camera/globals.wgsl"
#include "include/math/constants.wgsl"
#include "include/math/random.wgsl"
#include "include/lighting/volumetric_light.wgsl"
#include "include/lighting/sun.wgsl"
#include "include/lighting/shadows.wgsl"
#include "include/lighting/ambient.wgsl"
#include "include/atmosphere/fog.wgsl"
#include "include/atmosphere/aerial_perspective.wgsl"
#include "include/material/pbr_lite.wgsl"
#include "include/material/voxel_material.wgsl"
#include "include/material/foliage_material.wgsl"
#include "include/voxel/face_variation.wgsl"
#include "include/voxel/triplanar.wgsl"
#include "include/voxel/ao.wgsl"
#include "include/camera/depth.wgsl"
#include "passes/terrain/terrain.frag.wgsl"


